### ISSUE TITLE
Add install section to Makefile

### ISSUE THREAD

**Issue by samedamci** [Titor8115/mandown#15]
I know, this is probably part of point "Makefile makeover" in TODO but this is important and simple to do. When you do that I can add and maintain package in AUR (Arch User Repository) if you want.

**Comment by Titor8115** [comment]
I was thinking about adding prefix paths for the man-page lookup, and that toke me sometime. But since Troff parser isn't going to be out for some time, I'll add the install section for the Makefile after fixing up some render issue after window resizing. So it would be pushed this weekend or coming week. 

And it would be lovely if you can add and maintain the package on AUR.

**Comment by Titor8115** [comment]
@samedamci I just uploaded the fixed version. And there is now an install section in ‘Makefile’.

I’m very experienced with Makefile. Feel free to make a pull request if you want to change anything.
