### ISSUE TITLE
React to window size changes

### ISSUE THREAD

**Issue by hellricer** [Titor8115/mandown#2]
Hey, first of all let me thank you for this project!

One of my biggest gripes with `man` is that the text is not "re-wrapped" when the window size changes. Because I'm using tiling managers, this is often problem as I have to quit `man` and run it again.

The reason is, of course, that `man` only sends output of `groff` to pager, so it's basically impossible to fix.

But maybe it could be implemented here?

**Comment by Titor8115** [comment]
Yep, re-wrapping is on my list of things to add next. Line-fold without breaking individual words is also on the list.

One that note, do you think refresh after window resize is better or while resizing?

**Comment by hellricer** [comment]
I'd be fine with both, but I was under impression that in ncurses you can only react to WINCH signal anyway. 

Whether the window is resized smoothly or not should be handled by terminal app or window manager (AFAIK).

**Comment by Titor8115** [comment]
Indeed, as far as I’m aware, Ncurses only reacts to WINCH signal. But the project uses pad as container of the markdown content, so if we can get pad content to a window for indentation rendering, instead of using ‘prefresh()’ on pad, that might do the trick.

**Comment by Titor8115** [comment]
> Indeed, as far as I’m aware, Ncurses only reacts to WINCH signal. But the project uses pad as container of the markdown content, so if we can get pad content to a window for indentation rendering, instead of using ‘prefresh()’ on pad, that might do the trick. 
> 
> Or!!!! We could do it the hard way by simply reprinting the content to the pad

Just added “re-wrapping” feature that react to terminal resize events. It repaint the indentation for the entire document after terminal resized.

After where WINCH signal would ends, I added a short delay before repainting. So that large documents, or people who resizing window for fun won’t accidentally overload the CPU (probably won’t happen anyway).

Since it is initial implement/hot fix. I do find that if resizing too fast, it might “forgets” to do the painting. If that happens, just resize the window for a column or row should fix it.

**Comment by Titor8115** [comment]
@hellricer Resizing and Line-wrap is fully supported now with smooth rendering. It should be the final version for this part of the feature.

Custom line-wrap support will be added next.
